# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55fd40d7a5b806cea3500d0aa01accc4e231d109d3e213a23dac261b950a8dba5d3df6f3ec5e58b40524d18f93f7e4917ededb362a67daefca2c9d973150ce1
  google_form_url: <%= ENV["GOOGLE_FORM_URL"] %>
  slack_webhook: <%= ENV["SLACK_WEBHOOK"] %>

test:
  secret_key_base: a74ccedfbe65dddd693f4ff118af80d69baab53929b57b67672163294acc6fc9aeb2a65c824df067462b9ea0dcfcddc34de2b156680947fbeb17a6e6a9ce37e9
  google_form_url: <%= ENV["GOOGLE_FORM_URL"] %>
  slack_webhook: <%= ENV["SLACK_WEBHOOK"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_form_url: <%= ENV["GOOGLE_FORM_URL"] %>
  slack_webhook: <%= ENV["SLACK_WEBHOOK"] %>
